### ISSUE TITLE
It won't work on intel integrated graphic card

### ISSUE THREAD

**Issue by deping** [vicrucann/QtOSG-hello#3]
It does work on Nvidia graphic card. but when I use an intel integrated graphic card or an AMD firepro M5100, it doesn't show any thing in window.
In the console, there is an line:
Error: OpenGL version test failed, requires valid graphics context.
It seems there is no graphic context in this case, but I don't know why.

```C++
GLExtensions::GLExtensions(unsigned int in_contextID):
    contextID(in_contextID)
{
    const char* versionString = (const char*) glGetString( GL_VERSION );
    bool validContext = versionString!=0;
    if (!validContext)
    {
        OSG_NOTIFY(osg::FATAL)<<"Error: OpenGL version test failed, requires valid graphics context."<<std::endl;
    }
```

**Comment by vicrucann** [comment]
What OpenGL version do you have? You may need to update your drivers. Are you able to run any code samples provided by OSG?

**Comment by deping** [comment]
Thanks, after installing latest graphics driver for intel graphics card, your example can show a cylinder now.
My application can work after I comment opengl version requirement:
```C++
    QSurfaceFormat format;
    format.setDepthBufferSize(24);
    format.setStencilBufferSize(8);
    //format.setVersion(3, 2);
    format.setProfile(QSurfaceFormat::CompatibilityProfile);
    QSurfaceFormat::setDefaultFormat(format);
```
